# Generated by Django 4.0.4 on 2022-05-09 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_txt', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Subinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subinfo_txt', models.CharField(max_length=300)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infoapp.info')),
            ],
        ),
    ]
